/* Interactive explanatory visualizations for Jev Explained. D3 is loaded by pages using this file. */
(function(){
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const C={bg:'#090d18',card:'#131a2c',soft:'#1a2338',text:'#f3f6fc',muted:'#aeb8cc',accent:'#8cb4ff',line:'#2a3652',green:'#8bd5a5',amber:'#e6b566'};
  function svgFor(sel,h=360){const el=d3.select(sel);el.selectAll('*').remove();const w=Math.max(320,el.node().clientWidth||800);return el.append('svg').attr('viewBox',`0 0 ${w} ${h}`).attr('role','img').style('width','100%').style('height','auto')}
  function box(svg,x,y,w,h,label,sub,fill=C.card){svg.append('rect').attr('x',x).attr('y',y).attr('width',w).attr('height',h).attr('rx',12).attr('fill',fill).attr('stroke',C.line);svg.append('text').attr('x',x+w/2).attr('y',y+h/2-(sub?8:0)).attr('text-anchor','middle').attr('fill',C.text).attr('font-weight',700).attr('font-size',14).text(label);if(sub)svg.append('text').attr('x',x+w/2).attr('y',y+h/2+14).attr('text-anchor','middle').attr('fill',C.muted).attr('font-size',11).text(sub)}
  function line(svg,x1,y1,x2,y2,delay=0){const p=svg.append('path').attr('d',`M${x1},${y1} L${x2},${y2}`).attr('stroke',C.accent).attr('stroke-width',2).attr('fill','none').attr('marker-end','url(#arrow)');if(!reduced){const len=p.node().getTotalLength();p.attr('stroke-dasharray',len).attr('stroke-dashoffset',len).transition().delay(delay).duration(600).attr('stroke-dashoffset',0)}}
  function defs(svg){svg.append('defs').append('marker').attr('id','arrow').attr('viewBox','0 0 10 10').attr('refX',9).attr('refY',5).attr('markerWidth',6).attr('markerHeight',6).attr('orient','auto-start-reverse').append('path').attr('d','M 0 0 L 10 5 L 0 10 z').attr('fill',C.accent)}
  window.JevViz={
    llmVsJev(sel){const el=document.querySelector(sel);if(!el)return;const svg=svgFor(sel,390),w=+svg.attr('viewBox').split(' ')[2];defs(svg);const mobile=w<600; if(mobile){box(svg,25,25,w-50,55,'Shared input','incident + schema');box(svg,25,110,w-50,55,'LLM prefill','understand context');box(svg,25,200,w-50,55,'Autoregressive decode','token → token → token → JSON');box(svg,25,300,w-50,55,'Jev-style readout','probabilities directly',C.soft);line(svg,w/2,80,w/2,110,100);line(svg,w/2,165,w/2,200,500);line(svg,w/2,165,w/2,300,700);return}
      box(svg,30,25,180,58,'Shared input','incident + decision schema');box(svg,30,145,180,65,'Transformer prefill','build semantic state');box(svg,w-250,65,210,70,'Typical LLM','generate output tokens');box(svg,w-250,255,210,70,'Decision readout','score allowed outcomes',C.soft);line(svg,120,83,120,145,100);line(svg,210,177,w-250,100,500);line(svg,210,177,w-250,290,650);svg.append('text').attr('x',w-145).attr('y',155).attr('text-anchor','middle').attr('fill',C.muted).attr('font-size',12).text('{ → risk → : → HIGH → …');svg.append('text').attr('x',w-145).attr('y',345).attr('text-anchor','middle').attr('fill',C.green).attr('font-size',12).text('HIGH .99 · MEDIUM .01 · LOW .00')},
    parallel(sel){const el=document.querySelector(sel);if(!el)return;const svg=svgFor(sel,420),w=+svg.attr('viewBox').split(' ')[2];defs(svg);box(svg,w/2-115,20,230,60,'Shared application state','processed once');box(svg,w/2-115,110,230,60,'Reusable representation','state / cache',C.soft);line(svg,w/2,80,w/2,110,100);const qs=w<600?[['Risk?',30],['Review?',w/2-70],['Action?',w-170]]:[['Risk?',70],['Review?',w/2-70],['Action?',w-210]];qs.forEach(([q,x],i)=>{box(svg,x,230,140,55,q,'isolated branch');line(svg,w/2,170,x+70,230,400+i*120);box(svg,x,330,140,55,['HIGH · .99','true · 1.00','TIER_2 · .98'][i],'probability');line(svg,x+70,285,x+70,330,900+i*100)})},
    logits(sel){const el=document.querySelector(sel);if(!el)return;const data=[['HIGH',.9924],['MEDIUM',.0068],['LOW',.0006],['NONE',.0002]];const svg=svgFor(sel,280),w=+svg.attr('viewBox').split(' ')[2],margin={l:75,r:60,t:25,b:25},iw=w-margin.l-margin.r;const x=d3.scaleLinear().domain([0,1]).range([0,iw]);data.forEach((d,i)=>{const y=35+i*52;svg.append('text').attr('x',margin.l-10).attr('y',y+15).attr('text-anchor','end').attr('fill',C.text).attr('font-size',12).text(d[0]);svg.append('rect').attr('x',margin.l).attr('y',y).attr('width',iw).attr('height',20).attr('rx',6).attr('fill',C.soft);const bar=svg.append('rect').attr('x',margin.l).attr('y',y).attr('width',reduced?x(d[1]):0).attr('height',20).attr('rx',6).attr('fill',i===0?C.green:C.accent);if(!reduced)bar.transition().delay(i*120).duration(800).attr('width',x(d[1]));svg.append('text').attr('x',w-margin.r+8).attr('y',y+15).attr('fill',C.muted).attr('font-size',11).text((d[1]*100).toFixed(2)+'%')})},
    choiceInteraction(sel){const el=document.querySelector(sel);if(!el)return;const svg=svgFor(sel,350),w=+svg.attr('viewBox').split(' ')[2];const before=[['bank',.55],['provider',.35],['customer',.10]],after=[['bank',.43],['provider',.37],['customer',.08],['unknown',.12]];const groups=[[before,35,'3 options'],[after,w/2+15,'add “unknown”']];groups.forEach(([data,x0,title],gi)=>{svg.append('text').attr('x',x0).attr('y',28).attr('fill',C.text).attr('font-weight',700).text(title);const maxW=Math.max(110,w/2-80);data.forEach((d,i)=>{const y=55+i*52;svg.append('text').attr('x',x0).attr('y',y+13).attr('fill',C.muted).attr('font-size',11).text(d[0]);const r=svg.append('rect').attr('x',x0+70).attr('y',y).attr('height',18).attr('rx',5).attr('fill',gi?C.amber:C.accent).attr('width',reduced?d[1]*maxW:0);if(!reduced)r.transition().delay(gi*500+i*80).duration(700).attr('width',d[1]*maxW);svg.append('text').attr('x',x0+75+d[1]*maxW).attr('y',y+13).attr('fill',C.text).attr('font-size',10).text(Math.round(d[1]*100)+'%')})});svg.append('text').attr('x',w/2).attr('y',320).attr('text-anchor','middle').attr('fill',C.muted).attr('font-size',11).text('Illustrative: changing the option set can change relative odds — evidence for listwise interaction')}
  };
})();